POST https://node-do-zero-5mv2.onrender.com/videos
Content-Type: application/json

{
    "title": "Video Node",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###
GET  https://node-do-zero-5mv2.onrender.com/videos

###
PUT https://node-do-zero-5mv2.onrender.com/videos/07dd08b3-d5e8-49ea-a03a-673f68b88630
Content-Type: application/json

{
    "title": "Video 02",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###
DELETE https://node-do-zero-5mv2.onrender.com/videos/07dd08b3-d5e8-49ea-a03a-673f68b88630